enum hotelsActionTypes {
  HOTELS_LOAD_START = "HOTELS_LOAD_START",
  HOTELS_LOAD_SUCCESS = "HOTELS_LOAD_SUCCESS",
  HOTEL_ROOMS_LOAD_START = "HOTEL_ROOMS_LOAD_START",
  HOTEL_ROOMS_LOAD_SUCCESS = "HOTEL_ROOMS_LOAD_SUCCESS",
}

export default hotelsActionTypes;
